package org.citygml4j.visitor;

import org.citygml4j.model.citygml.ade.ADEComponent;
import org.citygml4j.model.citygml.appearance.Appearance;
import org.citygml4j.model.citygml.appearance.GeoreferencedTexture;
import org.citygml4j.model.citygml.appearance.ParameterizedTexture;
import org.citygml4j.model.citygml.appearance.X3DMaterial;
import org.citygml4j.model.citygml.building.Building;
import org.citygml4j.model.citygml.building.BuildingFurniture;
import org.citygml4j.model.citygml.building.BuildingInstallation;
import org.citygml4j.model.citygml.building.BuildingPart;
import org.citygml4j.model.citygml.building.CeilingSurface;
import org.citygml4j.model.citygml.building.ClosureSurface;
import org.citygml4j.model.citygml.building.Door;
import org.citygml4j.model.citygml.building.FloorSurface;
import org.citygml4j.model.citygml.building.GroundSurface;
import org.citygml4j.model.citygml.building.IntBuildingInstallation;
import org.citygml4j.model.citygml.building.InteriorWallSurface;
import org.citygml4j.model.citygml.building.RoofSurface;
import org.citygml4j.model.citygml.building.Room;
import org.citygml4j.model.citygml.building.WallSurface;
import org.citygml4j.model.citygml.building.Window;
import org.citygml4j.model.citygml.cityfurniture.CityFurniture;
import org.citygml4j.model.citygml.cityobjectgroup.CityObjectGroup;
import org.citygml4j.model.citygml.core.Address;
import org.citygml4j.model.citygml.core.CityModel;
import org.citygml4j.model.citygml.generics.GenericCityObject;
import org.citygml4j.model.citygml.landuse.LandUse;
import org.citygml4j.model.citygml.relief.BreaklineRelief;
import org.citygml4j.model.citygml.relief.MassPointRelief;
import org.citygml4j.model.citygml.relief.RasterRelief;
import org.citygml4j.model.citygml.relief.ReliefFeature;
import org.citygml4j.model.citygml.relief.TINRelief;
import org.citygml4j.model.citygml.transportation.AuxiliaryTrafficArea;
import org.citygml4j.model.citygml.transportation.Railway;
import org.citygml4j.model.citygml.transportation.Road;
import org.citygml4j.model.citygml.transportation.Square;
import org.citygml4j.model.citygml.transportation.Track;
import org.citygml4j.model.citygml.transportation.TrafficArea;
import org.citygml4j.model.citygml.transportation.TransportationComplex;
import org.citygml4j.model.citygml.vegetation.PlantCover;
import org.citygml4j.model.citygml.vegetation.SolitaryVegetationObject;
import org.citygml4j.model.citygml.waterbody.WaterBody;
import org.citygml4j.model.citygml.waterbody.WaterClosureSurface;
import org.citygml4j.model.citygml.waterbody.WaterGroundSurface;
import org.citygml4j.model.citygml.waterbody.WaterSurface;
import org.citygml4j.model.gml.RectifiedGridCoverage;
import org.citygml4j.xml.schema.ElementDecl;
import org.w3c.dom.Element;

public interface FeatureVisitor {
	public void accept(Appearance appearance);
	public void accept(GeoreferencedTexture georeferencedTexture);
	public void accept(ParameterizedTexture parameterizedTexture);
	public void accept(X3DMaterial x3dMaterial);
	public void accept(BuildingFurniture buildingFurniture);
	public void accept(Building building);
	public void accept(BuildingInstallation buildingInstallation);
	public void accept(BuildingPart buildingPart);
	public void accept(CeilingSurface ceilingSurface);
	public void accept(ClosureSurface closureSurface);
	public void accept(Door door);
	public void accept(FloorSurface floorSurface);
	public void accept(GroundSurface groundSurface);
	public void accept(IntBuildingInstallation intBuildingInstallation);
	public void accept(InteriorWallSurface interiorWallSurface);
	public void accept(RoofSurface roofSurface);
	public void accept(Room room);
	public void accept(WallSurface wallSurface);
	public void accept(Window window);
	public void accept(CityFurniture cityFurniture);
	public void accept(CityObjectGroup cityObjectGroup);
	public void accept(Address address);
	public void accept(CityModel cityModel);
	public void accept(GenericCityObject genericCityObject);
	public void accept(LandUse landUse);
	public void accept(BreaklineRelief breaklineRelief);
	public void accept(MassPointRelief massPointRelief);
	public void accept(RasterRelief rasterRelief);
	public void accept(ReliefFeature reliefFeature);
	public void accept(TINRelief tinRelief);
	public void accept(AuxiliaryTrafficArea auxiliaryTrafficArea);
	public void accept(Railway railway);
	public void accept(RectifiedGridCoverage rectifiedGridCoverage);
	public void accept(Road road);
	public void accept(Square square);
	public void accept(Track track);
	public void accept(TrafficArea trafficArea);
	public void accept(TransportationComplex transportationComplex);
	public void accept(PlantCover plantCover);
	public void accept(SolitaryVegetationObject solitaryVegetationObject);
	public void accept(WaterBody waterBody);
	public void accept(WaterClosureSurface waterClosureSurface);
	public void accept(WaterGroundSurface waterGroundSurface);
	public void accept(WaterSurface waterSurface);
	public void accept(ADEComponent adeComponent);
	public void accept(Element element, ElementDecl decl);
}
