package org.citygml4j.visitor;

import org.citygml4j.model.citygml.ade.ADEComponent;
import org.citygml4j.model.citygml.appearance.Appearance;
import org.citygml4j.model.citygml.appearance.GeoreferencedTexture;
import org.citygml4j.model.citygml.appearance.ParameterizedTexture;
import org.citygml4j.model.citygml.appearance.X3DMaterial;
import org.citygml4j.model.citygml.building.Building;
import org.citygml4j.model.citygml.building.BuildingFurniture;
import org.citygml4j.model.citygml.building.BuildingInstallation;
import org.citygml4j.model.citygml.building.BuildingPart;
import org.citygml4j.model.citygml.building.CeilingSurface;
import org.citygml4j.model.citygml.building.ClosureSurface;
import org.citygml4j.model.citygml.building.Door;
import org.citygml4j.model.citygml.building.FloorSurface;
import org.citygml4j.model.citygml.building.GroundSurface;
import org.citygml4j.model.citygml.building.IntBuildingInstallation;
import org.citygml4j.model.citygml.building.InteriorWallSurface;
import org.citygml4j.model.citygml.building.RoofSurface;
import org.citygml4j.model.citygml.building.Room;
import org.citygml4j.model.citygml.building.WallSurface;
import org.citygml4j.model.citygml.building.Window;
import org.citygml4j.model.citygml.cityfurniture.CityFurniture;
import org.citygml4j.model.citygml.cityobjectgroup.CityObjectGroup;
import org.citygml4j.model.citygml.core.Address;
import org.citygml4j.model.citygml.core.CityModel;
import org.citygml4j.model.citygml.generics.GenericCityObject;
import org.citygml4j.model.citygml.landuse.LandUse;
import org.citygml4j.model.citygml.relief.BreaklineRelief;
import org.citygml4j.model.citygml.relief.MassPointRelief;
import org.citygml4j.model.citygml.relief.RasterRelief;
import org.citygml4j.model.citygml.relief.ReliefFeature;
import org.citygml4j.model.citygml.relief.TINRelief;
import org.citygml4j.model.citygml.transportation.AuxiliaryTrafficArea;
import org.citygml4j.model.citygml.transportation.Railway;
import org.citygml4j.model.citygml.transportation.Road;
import org.citygml4j.model.citygml.transportation.Square;
import org.citygml4j.model.citygml.transportation.Track;
import org.citygml4j.model.citygml.transportation.TrafficArea;
import org.citygml4j.model.citygml.transportation.TransportationComplex;
import org.citygml4j.model.citygml.vegetation.PlantCover;
import org.citygml4j.model.citygml.vegetation.SolitaryVegetationObject;
import org.citygml4j.model.citygml.waterbody.WaterBody;
import org.citygml4j.model.citygml.waterbody.WaterClosureSurface;
import org.citygml4j.model.citygml.waterbody.WaterGroundSurface;
import org.citygml4j.model.citygml.waterbody.WaterSurface;
import org.citygml4j.model.gml.coverage.RectifiedGridCoverage;
import org.citygml4j.xml.schema.ElementDecl;
import org.w3c.dom.Element;

public interface FeatureFunction<T> {
	public T accept(Appearance appearance);
	public T accept(GeoreferencedTexture georeferencedTexture);
	public T accept(ParameterizedTexture parameterizedTexture);
	public T accept(X3DMaterial x3dMaterial);
	public T accept(BuildingFurniture buildingFurniture);
	public T accept(Building building);
	public T accept(BuildingInstallation buildingInstallation);
	public T accept(BuildingPart buildingPart);
	public T accept(CeilingSurface ceilingSurface);
	public T accept(ClosureSurface closureSurface);
	public T accept(Door door);
	public T accept(FloorSurface floorSurface);
	public T accept(GroundSurface groundSurface);
	public T accept(IntBuildingInstallation intBuildingInstallation);
	public T accept(InteriorWallSurface interiorWallSurface);
	public T accept(RoofSurface roofSurface);
	public T accept(Room room);
	public T accept(WallSurface wallSurface);
	public T accept(Window window);
	public T accept(CityFurniture cityFurniture);
	public T accept(CityObjectGroup cityObjectGroup);
	public T accept(Address address);
	public T accept(CityModel cityModel);
	public T accept(GenericCityObject genericCityObject);
	public T accept(LandUse landUse);
	public T accept(BreaklineRelief breaklineRelief);
	public T accept(MassPointRelief massPointRelief);
	public T accept(RasterRelief rasterRelief);
	public T accept(ReliefFeature reliefFeature);
	public T accept(TINRelief tinRelief);
	public T accept(AuxiliaryTrafficArea auxiliaryTrafficArea);
	public T accept(Railway railway);
	public T accept(RectifiedGridCoverage rectifiedGridCoverage);
	public T accept(Road road);
	public T accept(Square square);
	public T accept(Track track);
	public T accept(TrafficArea trafficArea);
	public T accept(TransportationComplex transportationComplex);
	public T accept(PlantCover plantCover);
	public T accept(SolitaryVegetationObject solitaryVegetationObject);
	public T accept(WaterBody waterBody);
	public T accept(WaterClosureSurface waterClosureSurface);
	public T accept(WaterGroundSurface waterGroundSurface);
	public T accept(WaterSurface waterSurface);
	public T accept(ADEComponent adeComponent);
	public T accept(Element element, ElementDecl decl);
}
