package org.citygml4j.visitor;

import org.citygml4j.model.citygml.texturedsurface._TexturedSurface;
import org.citygml4j.model.gml.geometry.aggregates.MultiCurve;
import org.citygml4j.model.gml.geometry.aggregates.MultiLineString;
import org.citygml4j.model.gml.geometry.aggregates.MultiPoint;
import org.citygml4j.model.gml.geometry.aggregates.MultiPolygon;
import org.citygml4j.model.gml.geometry.aggregates.MultiSolid;
import org.citygml4j.model.gml.geometry.aggregates.MultiSurface;
import org.citygml4j.model.gml.geometry.complexes.CompositeCurve;
import org.citygml4j.model.gml.geometry.complexes.CompositeSolid;
import org.citygml4j.model.gml.geometry.complexes.CompositeSurface;
import org.citygml4j.model.gml.geometry.complexes.GeometricComplex;
import org.citygml4j.model.gml.geometry.primitives.Curve;
import org.citygml4j.model.gml.geometry.primitives.LineString;
import org.citygml4j.model.gml.geometry.primitives.LinearRing;
import org.citygml4j.model.gml.geometry.primitives.OrientableCurve;
import org.citygml4j.model.gml.geometry.primitives.OrientableSurface;
import org.citygml4j.model.gml.geometry.primitives.Point;
import org.citygml4j.model.gml.geometry.primitives.Polygon;
import org.citygml4j.model.gml.geometry.primitives.Ring;
import org.citygml4j.model.gml.geometry.primitives.Solid;
import org.citygml4j.model.gml.geometry.primitives.Surface;
import org.citygml4j.model.gml.geometry.primitives.Tin;
import org.citygml4j.model.gml.geometry.primitives.TriangulatedSurface;
import org.citygml4j.model.gml.grids.Grid;
import org.citygml4j.model.gml.grids.RectifiedGrid;

public interface GeometryVisitor {
	public void accept(CompositeCurve compositeCurve);
	public void accept(CompositeSolid compositeSolid);
	public void accept(CompositeSurface compositeSurface);
	public void accept(Curve curve);
	public void accept(GeometricComplex geometricComplex);
	public void accept(Grid grid);
	public void accept(LinearRing linearRing);
	public void accept(LineString lineString);
	public void accept(MultiCurve multiCurve);
	public void accept(MultiLineString multiLineString);
	public void accept(MultiPoint multiPoint);
	public void accept(MultiPolygon multiPolygon);
	public void accept(MultiSolid multiSolid);
	public void accept(MultiSurface multiSurface);
	public void accept(OrientableCurve orientableCurve);
	public void accept(OrientableSurface orientableSurface);
	public void accept(_TexturedSurface texturedSurface);
	public void accept(Point point);
	public void accept(Polygon polygon);
	public void accept(RectifiedGrid rectifiedGrid);
	public void accept(Ring ring);
	public void accept(Solid solid);
	public void accept(Surface surface);
	public void accept(Tin tin);
	public void accept(TriangulatedSurface triangulatedSurface);
}
