package org.citygml4j.visitor;

import org.citygml4j.model.citygml.texturedsurface._TexturedSurface;
import org.citygml4j.model.gml.geometry.aggregates.MultiCurve;
import org.citygml4j.model.gml.geometry.aggregates.MultiLineString;
import org.citygml4j.model.gml.geometry.aggregates.MultiPoint;
import org.citygml4j.model.gml.geometry.aggregates.MultiPolygon;
import org.citygml4j.model.gml.geometry.aggregates.MultiSolid;
import org.citygml4j.model.gml.geometry.aggregates.MultiSurface;
import org.citygml4j.model.gml.geometry.complexes.CompositeCurve;
import org.citygml4j.model.gml.geometry.complexes.CompositeSolid;
import org.citygml4j.model.gml.geometry.complexes.CompositeSurface;
import org.citygml4j.model.gml.geometry.complexes.GeometricComplex;
import org.citygml4j.model.gml.geometry.primitives.Curve;
import org.citygml4j.model.gml.geometry.primitives.LineString;
import org.citygml4j.model.gml.geometry.primitives.LinearRing;
import org.citygml4j.model.gml.geometry.primitives.OrientableCurve;
import org.citygml4j.model.gml.geometry.primitives.OrientableSurface;
import org.citygml4j.model.gml.geometry.primitives.Point;
import org.citygml4j.model.gml.geometry.primitives.Polygon;
import org.citygml4j.model.gml.geometry.primitives.Ring;
import org.citygml4j.model.gml.geometry.primitives.Solid;
import org.citygml4j.model.gml.geometry.primitives.Surface;
import org.citygml4j.model.gml.geometry.primitives.Tin;
import org.citygml4j.model.gml.geometry.primitives.TriangulatedSurface;
import org.citygml4j.model.gml.grids.Grid;
import org.citygml4j.model.gml.grids.RectifiedGrid;

public interface GeometryFunction<T> {
	public T accept(CompositeCurve compositeCurve);
	public T accept(CompositeSolid compositeSolid);
	public T accept(CompositeSurface compositeSurface);
	public T accept(Curve curve);
	public T accept(GeometricComplex geometricComplex);
	public T accept(Grid grid);
	public T accept(LinearRing linearRing);
	public T accept(LineString lineString);
	public T accept(MultiCurve multiCurve);
	public T accept(MultiLineString multiLineString);
	public T accept(MultiPoint multiPoint);
	public T accept(MultiPolygon multiPolygon);
	public T accept(MultiSolid multiSolid);
	public T accept(MultiSurface multiSurface);
	public T accept(OrientableCurve orientableCurve);
	public T accept(OrientableSurface orientableSurface);
	public T accept(_TexturedSurface texturedSurface);
	public T accept(Point point);
	public T accept(Polygon polygon);
	public T accept(RectifiedGrid rectifiedGrid);
	public T accept(Ring ring);
	public T accept(Solid solid);
	public T accept(Surface surface);
	public T accept(Tin tin);
	public T accept(TriangulatedSurface triangulatedSurface);
}
