package org.citygml4j.visitor;

import org.citygml4j.model.xal.Address;
import org.citygml4j.model.xal.AddressDetails;
import org.citygml4j.model.xal.AddressIdentifier;
import org.citygml4j.model.xal.AddressLatitude;
import org.citygml4j.model.xal.AddressLatitudeDirection;
import org.citygml4j.model.xal.AddressLine;
import org.citygml4j.model.xal.AddressLines;
import org.citygml4j.model.xal.AddressLongitude;
import org.citygml4j.model.xal.AddressLongitudeDirection;
import org.citygml4j.model.xal.AdministrativeArea;
import org.citygml4j.model.xal.AdministrativeAreaName;
import org.citygml4j.model.xal.Barcode;
import org.citygml4j.model.xal.BuildingName;
import org.citygml4j.model.xal.Country;
import org.citygml4j.model.xal.CountryName;
import org.citygml4j.model.xal.CountryNameCode;
import org.citygml4j.model.xal.Department;
import org.citygml4j.model.xal.DepartmentName;
import org.citygml4j.model.xal.DependentLocality;
import org.citygml4j.model.xal.DependentLocalityName;
import org.citygml4j.model.xal.DependentLocalityNumber;
import org.citygml4j.model.xal.DependentThoroughfare;
import org.citygml4j.model.xal.EndorsementLineCode;
import org.citygml4j.model.xal.Firm;
import org.citygml4j.model.xal.FirmName;
import org.citygml4j.model.xal.KeyLineCode;
import org.citygml4j.model.xal.LargeMailUser;
import org.citygml4j.model.xal.LargeMailUserIdentifier;
import org.citygml4j.model.xal.LargeMailUserName;
import org.citygml4j.model.xal.Locality;
import org.citygml4j.model.xal.LocalityName;
import org.citygml4j.model.xal.MailStop;
import org.citygml4j.model.xal.MailStopName;
import org.citygml4j.model.xal.MailStopNumber;
import org.citygml4j.model.xal.PostBox;
import org.citygml4j.model.xal.PostBoxNumber;
import org.citygml4j.model.xal.PostBoxNumberExtension;
import org.citygml4j.model.xal.PostBoxNumberPrefix;
import org.citygml4j.model.xal.PostBoxNumberSuffix;
import org.citygml4j.model.xal.PostOffice;
import org.citygml4j.model.xal.PostOfficeName;
import org.citygml4j.model.xal.PostOfficeNumber;
import org.citygml4j.model.xal.PostTown;
import org.citygml4j.model.xal.PostTownName;
import org.citygml4j.model.xal.PostTownSuffix;
import org.citygml4j.model.xal.PostalCode;
import org.citygml4j.model.xal.PostalCodeNumber;
import org.citygml4j.model.xal.PostalCodeNumberExtension;
import org.citygml4j.model.xal.PostalRoute;
import org.citygml4j.model.xal.PostalRouteName;
import org.citygml4j.model.xal.PostalRouteNumber;
import org.citygml4j.model.xal.PostalServiceElements;
import org.citygml4j.model.xal.Premise;
import org.citygml4j.model.xal.PremiseLocation;
import org.citygml4j.model.xal.PremiseName;
import org.citygml4j.model.xal.PremiseNumber;
import org.citygml4j.model.xal.PremiseNumberPrefix;
import org.citygml4j.model.xal.PremiseNumberRange;
import org.citygml4j.model.xal.PremiseNumberRangeFrom;
import org.citygml4j.model.xal.PremiseNumberRangeTo;
import org.citygml4j.model.xal.PremiseNumberSuffix;
import org.citygml4j.model.xal.SortingCode;
import org.citygml4j.model.xal.SubAdministrativeArea;
import org.citygml4j.model.xal.SubAdministrativeAreaName;
import org.citygml4j.model.xal.SubPremise;
import org.citygml4j.model.xal.SubPremiseLocation;
import org.citygml4j.model.xal.SubPremiseName;
import org.citygml4j.model.xal.SubPremiseNumber;
import org.citygml4j.model.xal.SubPremiseNumberPrefix;
import org.citygml4j.model.xal.SubPremiseNumberSuffix;
import org.citygml4j.model.xal.SupplementaryPostalServiceData;
import org.citygml4j.model.xal.Thoroughfare;
import org.citygml4j.model.xal.ThoroughfareLeadingType;
import org.citygml4j.model.xal.ThoroughfareName;
import org.citygml4j.model.xal.ThoroughfareNumber;
import org.citygml4j.model.xal.ThoroughfareNumberFrom;
import org.citygml4j.model.xal.ThoroughfareNumberPrefix;
import org.citygml4j.model.xal.ThoroughfareNumberRange;
import org.citygml4j.model.xal.ThoroughfareNumberSuffix;
import org.citygml4j.model.xal.ThoroughfareNumberTo;
import org.citygml4j.model.xal.ThoroughfarePostDirection;
import org.citygml4j.model.xal.ThoroughfarePreDirection;
import org.citygml4j.model.xal.ThoroughfareTrailingType;

public interface XALVisitor {
	public void accept(Address address);
	public void accept(AddressDetails addressDetails);
	public void accept(AddressIdentifier addressIdentifier);
	public void accept(AddressLatitude addressLatitude);
	public void accept(AddressLatitudeDirection addressLatitudeDirection);
	public void accept(AddressLine addressLine);
	public void accept(AddressLines addressLines);
	public void accept(AddressLongitude addressLongitude);
	public void accept(AddressLongitudeDirection addressLongitudeDirection);
	public void accept(AdministrativeArea administrativeArea);
	public void accept(AdministrativeAreaName administrativeAreaName);
	public void accept(Barcode barcode);
	public void accept(BuildingName buildingName);
	public void accept(Country country);
	public void accept(CountryName countryName);
	public void accept(CountryNameCode countryNameCode);
	public void accept(Department department);
	public void accept(DepartmentName departmentName);
	public void accept(DependentLocality dependentLocality);
	public void accept(DependentLocalityName dependentLocalityName);
	public void accept(DependentLocalityNumber dependentLocalityNumber);
	public void accept(DependentThoroughfare dependentThoroughfare);
	public void accept(EndorsementLineCode endorsementLineCode);
	public void accept(Firm firm);
	public void accept(FirmName firmName);
	public void accept(KeyLineCode keyLineCode);
	public void accept(LargeMailUser largeMailUser);
	public void accept(LargeMailUserIdentifier largeMailUserIdentifier);
	public void accept(LargeMailUserName largeMailUserName);
	public void accept(Locality locality);
	public void accept(LocalityName localityName);
	public void accept(MailStop mailStop);
	public void accept(MailStopName mailStopName);
	public void accept(MailStopNumber mailStopNumber);
	public void accept(PostalCode postalCode);
	public void accept(PostalCodeNumber postalCodeNumber);
	public void accept(PostalCodeNumberExtension postalCodeNumberExtension);
	public void accept(PostalRoute postalRoute);
	public void accept(PostalRouteName postalRouteName);
	public void accept(PostalRouteNumber postalRouteNumber);
	public void accept(PostalServiceElements postalServiceElements);
	public void accept(PostBox postBox);
	public void accept(PostBoxNumber postBoxNumber);
	public void accept(PostBoxNumberExtension postBoxNumberExtension);
	public void accept(PostBoxNumberPrefix postBoxNumberPrefix);
	public void accept(PostBoxNumberSuffix postBoxNumberSuffix);
	public void accept(PostOffice postOffice);
	public void accept(PostOfficeName postOfficeName);
	public void accept(PostOfficeNumber postOfficeNumber);
	public void accept(PostTown postTown);
	public void accept(PostTownName postTownName);
	public void accept(PostTownSuffix postTownSuffix);
	public void accept(Premise premise);
	public void accept(PremiseLocation premiseLocation);
	public void accept(PremiseName premiseName);
	public void accept(PremiseNumber premiseNumber);
	public void accept(PremiseNumberPrefix premiseNumberPrefix);
	public void accept(PremiseNumberRange premiseNumberRange);
	public void accept(PremiseNumberRangeFrom premiseNumberRangeFrom);
	public void accept(PremiseNumberRangeTo premiseNumberRangeTo);
	public void accept(PremiseNumberSuffix premiseNumberSuffix);
	public void accept(SortingCode sortingCode);
	public void accept(SubAdministrativeArea subAdministrativeArea);
	public void accept(SubAdministrativeAreaName subAdministrativeAreaName);
	public void accept(SubPremise subPremise);
	public void accept(SubPremiseLocation subPremiseLocation);
	public void accept(SubPremiseName subPremiseName);
	public void accept(SubPremiseNumber subPremiseNumber);
	public void accept(SubPremiseNumberPrefix subPremiseNumberPrefix);
	public void accept(SubPremiseNumberSuffix subPremiseNumberSuffix);
	public void accept(SupplementaryPostalServiceData supplementaryPostalServiceData);
	public void accept(Thoroughfare thoroughfare);
	public void accept(ThoroughfareLeadingType thoroughfareLeadingType);
	public void accept(ThoroughfareName thoroughfareName);
	public void accept(ThoroughfareNumber thoroughfareNumber);
	public void accept(ThoroughfareNumberFrom thoroughfareNumberFrom);
	public void accept(ThoroughfareNumberPrefix thoroughfareNumberPrefix);
	public void accept(ThoroughfareNumberRange thoroughfareNumberRange);
	public void accept(ThoroughfareNumberSuffix thoroughfareNumberSuffix);
	public void accept(ThoroughfareNumberTo thoroughfareNumberTo);
	public void accept(ThoroughfarePostDirection thoroughfarePostDirection);
	public void accept(ThoroughfarePreDirection thoroughfarePreDirection);
	public void accept(ThoroughfareTrailingType thoroughfareTrailingType);
}
