package org.citygml4j.model.xal;

import java.util.List;

public interface Thoroughfare extends XALBase {
	public List<AddressLine> getAddressLine();
	public List<Object> getThoroughfareNumberOrThoroughfareNumberRange();
	public List<ThoroughfareNumberPrefix> getThoroughfareNumberPrefix();
	public List<ThoroughfareNumberSuffix> getThoroughfareNumberSuffix();
	public ThoroughfarePreDirection getThoroughfarePreDirection();
	public ThoroughfareLeadingType getThoroughfareLeadingType();
	public List<ThoroughfareName> getThoroughfareName();
	public ThoroughfareTrailingType getThoroughfareTrailingType();
	public ThoroughfarePostDirection getThoroughfarePostDirection();
	public DependentThoroughfare getDependentThoroughfare();
	public DependentLocality getDependentLocality();
	public Premise getPremise();
	public Firm getFirm();
	public PostalCode getPostalCode();
	public String getType();
	public String getDependentThoroughfares();
	public String getDependentThoroughfaresIndicator();
	public String getDependentThoroughfaresConnector();
	public String getDependentThoroughfaresType();
	public boolean isSetAddressLine();
	public boolean isSetThoroughfareNumberOrThoroughfareNumberRange();
	public boolean isSetThoroughfareNumberPrefix();
	public boolean isSetThoroughfareNumberSuffix();
	public boolean isSetThoroughfarePreDirection();
	public boolean isSetThoroughfareLeadingType();
	public boolean isSetThoroughfareName();
	public boolean isSetThoroughfareTrailingType();
	public boolean isSetThoroughfarePostDirection();
	public boolean isSetDependentThoroughfare();
	public boolean isSetDependentLocality();
	public boolean isSetPremise();
	public boolean isSetFirm();
	public boolean isSetPostalCode();
	public boolean isSetType();
	public boolean isSetDependentThoroughfares();
	public boolean isSetDependentThoroughfaresIndicator();
	public boolean isSetDependentThoroughfaresConnector();
	public boolean isSetDependentThoroughfaresType();
	
	public void addAddressLine(AddressLine addressLine);
	public void setAddressLine(List<AddressLine> addressLine);
	public void addThoroughfareNumber(ThoroughfareNumber thoroughfareNumber);
	public void addThoroughfareNumberRange(ThoroughfareNumberRange thoroughfareNumberRange);
	public void addThoroughfareNumberPrefix(ThoroughfareNumberPrefix thoroughfareNumberPrefix);
	public void setThoroughfareNumberPrefix(List<ThoroughfareNumberPrefix> thoroughfareNumberPrefix);
	public void addThoroughfareNumberSuffix(ThoroughfareNumberSuffix thoroughfareNumberSuffix);
	public void setThoroughfareNumberSuffix(List<ThoroughfareNumberSuffix> thoroughfareNumberSuffix);
	public void setThoroughfarePreDirection(ThoroughfarePreDirection thoroughfarePreDirection);
	public void setThoroughfareLeadingType(ThoroughfareLeadingType thoroughfareLeadingType);
	public void addThoroughfareName(ThoroughfareName thoroughfareName);
	public void setThoroughfareName(List<ThoroughfareName> thoroughfareName);
	public void setThoroughfareTrailingType(ThoroughfareTrailingType thoroughfareTrailingType);
	public void setThoroughfarePostDirection(ThoroughfarePostDirection thoroughfarePostDirection);
	public void setDependentThoroughfare(DependentThoroughfare dependentThoroughfare);
	public void setDependentLocality(DependentLocality dependentLocality);
	public void setPremise(Premise premise);
	public void setFirm(Firm firm);
	public void setPostalCode(PostalCode postalCode);
	public void setType(String type);
	public void setDependentThoroughfares(String dependentThoroughfares);
	public void setDependentThoroughfaresIndicator(String dependentThoroughfaresIndicator);
	public void setDependentThoroughfaresConnector(String dependentThoroughfaresConnector);
	public void setDependentThoroughfaresType(String dependentThoroughfaresType);
	public void unsetAddressLine();
	public boolean unsetAddressLine(AddressLine addressLine);
	public void unsetThoroughfareNumberOrThoroughfareNumberRange();
	public void unsetThoroughfareNumberPrefix();
	public boolean unsetThoroughfareNumberPrefix(ThoroughfareNumberPrefix thoroughfareNumberPrefix);
	public void unsetThoroughfareNumberSuffix();
	public boolean unsetThoroughfareNumberSuffix(ThoroughfareNumberSuffix thoroughfareNumberSuffix);
	public void unsetThoroughfarePreDirection();
	public void unsetThoroughfareLeadingType();
	public void unsetThoroughfareName();
	public boolean unsetThoroughfareName(ThoroughfareName thoroughfareName);
	public void unsetThoroughfareTrailingType();
	public void unsetThoroughfarePostDirection();
	public void unsetDependentThoroughfare();
	public void unsetDependentLocality();
	public void unsetPremise();
	public void unsetFirm();
	public void unsetPostalCode();
	public void unsetType();
	public void unsetDependentThoroughfares();
	public void unsetDependentThoroughfaresIndicator();
	public void unsetDependentThoroughfaresConnector();
	public void unsetDependentThoroughfaresType();
}
