module org.citygml4j {
    requires transitive org.xmlobjects.gml;
    requires transitive org.xmlobjects.xal;

    exports org.citygml4j;
    exports org.citygml4j.ade;
    exports org.citygml4j.model;
    exports org.citygml4j.model.ade;
    exports org.citygml4j.model.ade.generic;
    exports org.citygml4j.model.appearance;
    exports org.citygml4j.model.bridge;
    exports org.citygml4j.model.building;
    exports org.citygml4j.model.cityfurniture;
    exports org.citygml4j.model.cityobjectgroup;
    exports org.citygml4j.model.common;
    exports org.citygml4j.model.construction;
    exports org.citygml4j.model.core;
    exports org.citygml4j.model.deprecated;
    exports org.citygml4j.model.deprecated.appearance;
    exports org.citygml4j.model.deprecated.bridge;
    exports org.citygml4j.model.deprecated.building;
    exports org.citygml4j.model.deprecated.cityfurniture;
    exports org.citygml4j.model.deprecated.cityobjectgroup;
    exports org.citygml4j.model.deprecated.construction;
    exports org.citygml4j.model.deprecated.core;
    exports org.citygml4j.model.deprecated.generics;
    exports org.citygml4j.model.deprecated.transportation;
    exports org.citygml4j.model.deprecated.tunnel;
    exports org.citygml4j.model.deprecated.vegetation;
    exports org.citygml4j.model.deprecated.waterbody;
    exports org.citygml4j.model.dynamizer;
    exports org.citygml4j.model.generics;
    exports org.citygml4j.model.landuse;
    exports org.citygml4j.model.pointcloud;
    exports org.citygml4j.model.relief;
    exports org.citygml4j.model.transportation;
    exports org.citygml4j.model.tunnel;
    exports org.citygml4j.model.vegetation;
    exports org.citygml4j.model.versioning;
    exports org.citygml4j.model.waterbody;
    exports org.citygml4j.util;
    exports org.citygml4j.util.geometry;
    exports org.citygml4j.util.reference;
    exports org.citygml4j.visitor;
    exports org.citygml4j.xml.adapter;
    exports org.citygml4j.xml.adapter.ade;
    exports org.citygml4j.xml.adapter.appearance;
    exports org.citygml4j.xml.adapter.bridge;
    exports org.citygml4j.xml.adapter.building;
    exports org.citygml4j.xml.adapter.cityfurniture;
    exports org.citygml4j.xml.adapter.cityobjectgroup;
    exports org.citygml4j.xml.adapter.construction;
    exports org.citygml4j.xml.adapter.core;
    exports org.citygml4j.xml.adapter.deprecated.appearance;
    exports org.citygml4j.xml.adapter.deprecated.bridge;
    exports org.citygml4j.xml.adapter.deprecated.building;
    exports org.citygml4j.xml.adapter.deprecated.cityobjectgroup;
    exports org.citygml4j.xml.adapter.deprecated.core;
    exports org.citygml4j.xml.adapter.deprecated.transportation;
    exports org.citygml4j.xml.adapter.deprecated.tunnel;
    exports org.citygml4j.xml.adapter.deprecated.waterbody;
    exports org.citygml4j.xml.adapter.dynamizer;
    exports org.citygml4j.xml.adapter.generics;
    exports org.citygml4j.xml.adapter.landuse;
    exports org.citygml4j.xml.adapter.pointcloud;
    exports org.citygml4j.xml.adapter.relief;
    exports org.citygml4j.xml.adapter.transportation;
    exports org.citygml4j.xml.adapter.tunnel;
    exports org.citygml4j.xml.adapter.vegetation;
    exports org.citygml4j.xml.adapter.versioning;
    exports org.citygml4j.xml.adapter.waterbody;
    exports org.citygml4j.xml.converter;
    exports org.citygml4j.xml.module;
    exports org.citygml4j.xml.module.ade;
    exports org.citygml4j.xml.module.citygml;
    exports org.citygml4j.xml.module.gml;
    exports org.citygml4j.xml.module.xal;
    exports org.citygml4j.xml.reader;
    exports org.citygml4j.xml.schema;
    exports org.citygml4j.xml.transform;
    exports org.citygml4j.xml.writer;

    opens org.citygml4j.model to org.xmlobjects;
    opens org.citygml4j.model.ade to org.xmlobjects;
    opens org.citygml4j.model.ade.generic to org.xmlobjects;
    opens org.citygml4j.model.appearance to org.xmlobjects;
    opens org.citygml4j.model.bridge to org.xmlobjects;
    opens org.citygml4j.model.building to org.xmlobjects;
    opens org.citygml4j.model.cityfurniture to org.xmlobjects;
    opens org.citygml4j.model.cityobjectgroup to org.xmlobjects;
    opens org.citygml4j.model.common to org.xmlobjects;
    opens org.citygml4j.model.construction to org.xmlobjects;
    opens org.citygml4j.model.core to org.xmlobjects;
    opens org.citygml4j.model.deprecated to org.xmlobjects;
    opens org.citygml4j.model.deprecated.appearance to org.xmlobjects;
    opens org.citygml4j.model.deprecated.bridge to org.xmlobjects;
    opens org.citygml4j.model.deprecated.building to org.xmlobjects;
    opens org.citygml4j.model.deprecated.cityfurniture to org.xmlobjects;
    opens org.citygml4j.model.deprecated.cityobjectgroup to org.xmlobjects;
    opens org.citygml4j.model.deprecated.construction to org.xmlobjects;
    opens org.citygml4j.model.deprecated.core to org.xmlobjects;
    opens org.citygml4j.model.deprecated.generics to org.xmlobjects;
    opens org.citygml4j.model.deprecated.transportation to org.xmlobjects;
    opens org.citygml4j.model.deprecated.tunnel to org.xmlobjects;
    opens org.citygml4j.model.deprecated.vegetation to org.xmlobjects;
    opens org.citygml4j.model.deprecated.waterbody to org.xmlobjects;
    opens org.citygml4j.model.dynamizer to org.xmlobjects;
    opens org.citygml4j.model.generics to org.xmlobjects;
    opens org.citygml4j.model.landuse to org.xmlobjects;
    opens org.citygml4j.model.pointcloud to org.xmlobjects;
    opens org.citygml4j.model.relief to org.xmlobjects;
    opens org.citygml4j.model.transportation to org.xmlobjects;
    opens org.citygml4j.model.tunnel to org.xmlobjects;
    opens org.citygml4j.model.vegetation to org.xmlobjects;
    opens org.citygml4j.model.versioning to org.xmlobjects;
    opens org.citygml4j.model.waterbody to org.xmlobjects;
}