package org.citygml4j.model.citygml;

public enum CityGMLClass {
	UNDEFINED,
	ADE_COMPONENT,
	
	// Core
	ABSTRACT_CITY_OBJECT,
	ABSTRACT_SITE,
	ADDRESS,
	ADDRESS_PROPERTY,
	CITY_MODEL,
	CITY_OBJECT_MEMBER,
	EXTERNAL_OBJECT,
	EXTERNAL_REFERENCE,
	GENERALIZATION_RELATION,
	IMPLICIT_GEOMETRY,
	IMPLICIT_REPRESENTATION_PROPERTY,
	TRANSFORMATION_MATRIX_2X2,
	TRANSFORMATION_MATRIX_3X4,
	TRANSFORMATION_MATRIX_4X4,
	XAL_ADDRESS_PROPERTY_TYPE,	

	// Appearance
	ABSTRACT_SURFACE_DATA,
	ABSTRACT_TEXTURE,	
	ABSTRACT_TEXTURE_PARAMETERIZATION,
	APPEARANCE,
	APPEARANCE_MEMBER,
	APPEARANCE_PROPERTY,
	COLOR,
	COLOR_PLUS_OPACITY,
	GEOREFERENCED_TEXTURE,
	PARAMETERIZED_TEXTURE,
	SURFACE_DATA_PROPERTY,
	TEX_COORD_GEN,
	TEX_COORD_LIST,
	TEXTURE_ASSOCIATION,
	TEXTURE_COORDINATES,
	TEXTURE_TYPE,
	WORLD_TO_TEXTURE,
	WRAP_MODE,
	X3D_MATERIAL,
	
	// Building	
	ABSTRACT_BUILDING,
	ABSTRACT_BOUNDARY_SURFACE,
	ABSTRACT_OPENING,
	BOUNDARY_SURFACE_PROPERTY,
	BUILDING,
	BUILDING_FURNITURE,
	INTERIOR_FURNITURE_PROPERTY,
	BUILDING_INSTALLATION,
	BUILDING_INSTALLATION_PROPERTY,
	BUILDING_PART,
	BUILDING_PART_PROPERTY,
	INT_BUILDING_INSTALLATION,
	INT_BUILDING_INSTALLATION_PROPERTY,
	ROOM,	
	INTERIOR_ROOM_PROPERTY,
	CEILING_SURFACE,
	CLOSURE_SURFACE,
	FLOOR_SURFACE,
	GROUND_SURFACE,	
	INTERIOR_WALL_SURFACE,
	ROOF_SURFACE,
	WALL_SURFACE,	
	DOOR,
	WINDOW,	
	OPENING_PROPERTY,
	
	// CityFurniture
	CITY_FURNITURE,
	
	// CityObjectGroup
	CITY_OBJECT_GROUP,
	CITY_OBJECT_GROUP_MEMBER,
	CITY_OBJECT_GROUP_PARENT,
	
	// Generics
	ABSTRACT_GENERIC_ATTRIBUTE,
	GENERIC_CITY_OBJECT,
	DATE_ATTRIBUTE,
	DOUBLE_ATTRIBUTE,
	INT_ATTRIBUTE,
	STRING_ATTRIBUTE,
	URI_ATTRIBUTE,
	
	// LandUse
	LAND_USE,
	
	// Relief
	ABSTRACT_RELIEF_COMPONENT,
	RELIEF_FEATURE,
	BREAKLINE_RELIEF,
	GRID_PROPERTY,
	MASSPOINT_RELIEF,
	RASTER_RELIEF,
	TIN_RELIEF,
	RELIEF_COMPONENT_PROPERTY,
	TIN_PROPERTY,
	
	// Transportation
	ABSTRACT_TRANSPORTATION_OBJECT,
	TRANSPORTATION_COMPLEX,	
	AUXILIARY_TRAFFIC_AREA,	
	RAILWAY,	
	ROAD,
	SQUARE,	
	TRACK,
	TRAFFIC_AREA,
	AUXILIARY_TRAFFIC_AREA_PROPERTY,
	TRAFFIC_AREA_PROPERTY,
	
	// Vegetation	
	ABSTRACT_VEGETATION_OBJECT,
	PLANT_COVER,	
	SOLITARY_VEGETATION_OBJECT,
	
	// WaterBody	
	ABSTRACT_WATER_OBJECT,
	ABSTRACT_WATER_BOUNDARY_SURFACE,
	WATER_BODY,
	WATER_CLOSURE_SURFACE,
	WATER_GROUND_SURFACE,	
	WATER_SURFACE,
	BOUNDED_BY_WATER_SURFACE_PROPERTY,
	
	// TexturedSurface
	_ABSTRACT_APPEARANCE,
	_MATERIAL,
	_SIMPLE_TEXTURE,
	_TEXTURED_SURFACE,	
	_COLOR,
	_TEXTURE_TYPE,
	_APPEARANCE_PROPERTY	
}
