package org.citygml4j.model.citygml;

public enum CityGMLClass {
	UNDEFINED,
	ADECOMPONENT,
	
	// Core
	CITYOBJECT,
	CITYMODEL,
	ADDRESS,
	EXTERNALOBJECT,
	EXTERNALREFERENCE,
	IMPLICITGEOMETRY,
	SITE,
	ADDRESSPROPERTY,
	CITYOBJECTMEMBER,
	GENERALIZATIONRELATION,
	IMPLICITREPRESENTATIONPROPERTY,
	XALADDRESSPROPERTYTYPE,	
	TRANSFORMATIONMATRIX2X2,
	TRANSFORMATIONMATRIX3X4,
	TRANSFORMATIONMATRIX4X4,

	// Appearance
	APPEARANCE,
	ABSTRACTSURFACEDATA,
	ABSTRACTTEXTURE,	
	COLOR,
	COLORPLUSOPACITY,
	GEOREFERENCEDTEXTURE,
	PARAMETERIZEDTEXTURE,
	TEXTUREPARAMETERIZATION,
	TEXCOORDGEN,
	TEXCOORDLIST,
	TEXTURECOORDINATES,
	TEXTURETYPE,
	WORLDTOTEXTURE,
	WRAPMODE,
	X3DMATERIAL,
	APPEARANCEMEMBER,
	APPEARANCEPROPERTY,
	SURFACEDATAPROPERTY,
	TEXTUREASSOCIATION,
	
	// Building	
	ABSTRACTBUILDING,
	BUILDING,
	BUILDINGFURNITURE,
	BUILDINGINSTALLATION,
	BUILDINGPART,
	INTBUILDINGINSTALLATION,
	ROOM,	
	BOUNDARYSURFACE,
	CEILINGSURFACE,
	CLOSURESURFACE,
	FLOORSURFACE,
	GROUNDSURFACE,	
	INTERIORWALLSURFACE,
	ROOFSURFACE,
	WALLSURFACE,	
	OPENING,
	DOOR,
	WINDOW,	
	BOUNDARYSURFACEPROPERTY,
	BUILDINGINSTALLATIONPROPERTY,
	BUILDINGPARTPROPERTY,
	INTBUILDINGINSTALLATIONPROPERTY,
	INTERIORFURNITUREPROPERTY,
	INTERIORROOMPROPERTY,
	OPENINGPROPERTY,
	
	// CityFurniture
	CITYFURNITURE,
	
	// CityObjectGroup
	CITYOBJECTGROUP,
	CITYOBJECTGROUPMEMBER,
	CITYOBJECTGROUPPARENT,
	
	// Generics
	GENERICATTRIBUTE,
	GENERICCITYOBJECT,
	DATEATTRIBUTE,
	DOUBLEATTRIBUTE,
	INTATTRIBUTE,
	STRINGATTRIBUTE,
	URIATTRIBUTE,
	
	// LandUse
	LANDUSE,
	
	// Relief
	RELIEFCOMPONENT,
	RELIEFFEATURE,
	BREAKLINERELIEF,
	MASSPOINTRELIEF,
	RASTERRELIEF,
	TINRELIEF,
	RELIEFCOMPONENTPROPERTY,
	TINPROPERTY,
	
	// Transportation
	TRANSPORTATIONOBJECT,
	TRANSPORTATIONCOMPLEX,	
	AUXILIARYTRAFFICAREA,	
	RAILWAY,	
	ROAD,
	SQUARE,	
	TRACK,
	TRAFFICAREA,
	AUXILIARYTRAFFICAREAPROPERTY,
	TRAFFICAREAPROPERTY,
	
	// Vegetation	
	VEGETATIONOBJECT,
	PLANTCOVER,	
	SOLITARYVEGETATIONOBJECT,
	
	// WaterBody	
	WATEROBJECT,
	WATERBODY,
	WATERBOUNDARYSURFACE,
	WATERCLOSURESURFACE,
	WATERGROUNDSURFACE,	
	WATERSURFACE,
	BOUNDEDBYWATERSURFACEPROPERTY,
	
	// TexturedSurface
	_APPEARANCE,
	_MATERIAL,
	_SIMPLETEXTURE,
	_TEXTUREDSURFACE,	
	_COLOR,
	_TEXTURETYPE,
	_APPEARANCEPROPERTY	
}
