/*
 * This file is part of citygml4j.
 * Copyright (c) 2007 - 2010
 * Institute for Geodesy and Geoinformation Science
 * Technische Universitaet Berlin, Germany
 * http://www.igg.tu-berlin.de/
 *
 * The citygml4j library is free software:
 * you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see 
 * <http://www.gnu.org/licenses/>.
 */
package org.citygml4j.model.citygml;

import org.citygml4j.model.common.base.ModelClassEnum;

public enum CityGMLClass implements ModelClassEnum {
	UNDEFINED,
	ABSTRACT_GML_GEOMETRY,

	// ADE
	ADE_COMPONENT,

	// Core
	ABSTRACT_CITY_OBJECT,
	ABSTRACT_SITE,	
	ADDRESS,
	ADDRESS_PROPERTY,
	CITY_MODEL,
	CITY_OBJECT_MEMBER,
	EXTERNAL_OBJECT,
	EXTERNAL_REFERENCE,
	GENERALIZATION_RELATION,
	IMPLICIT_GEOMETRY,
	IMPLICIT_REPRESENTATION_PROPERTY,
	RELATIVE_TO_TERRAIN,
	RELATIVE_TO_WATER,
	TRANSFORMATION_MATRIX_2X2,
	TRANSFORMATION_MATRIX_3X4,
	TRANSFORMATION_MATRIX_4X4,
	XAL_ADDRESS_PROPERTY,	

	// Appearance
	ABSTRACT_SURFACE_DATA,
	ABSTRACT_TEXTURE,
	ABSTRACT_TEXTURE_PARAMETERIZATION,	
	APPEARANCE,
	APPEARANCE_MEMBER,
	APPEARANCE_PROPERTY,
	COLOR,
	COLOR_PLUS_OPACITY,
	GEOREFERENCED_TEXTURE,
	PARAMETERIZED_TEXTURE,
	SURFACE_DATA_PROPERTY,
	TEX_COORD_GEN,
	TEX_COORD_LIST,
	TEXTURE_ASSOCIATION,
	TEXTURE_COORDINATES,
	TEXTURE_TYPE,
	WORLD_TO_TEXTURE,
	WRAP_MODE,
	X3D_MATERIAL,

	// Construction
	ABSTRACT_BOUNDARY_SURFACE,
	ABSTRACT_OPENING,	
	BOUNDARY_SURFACE_PROPERTY,
	INTERIOR_FURNITURE_PROPERTY,
	CEILING_SURFACE,
	CLOSURE_SURFACE,
	FLOOR_SURFACE,
	OPENING_PROPERTY,
	OUTER_CEILING_SURFACE,
	OUTER_FLOOR_SURFACE,
	GROUND_SURFACE,	
	INTERIOR_WALL_SURFACE,
	ROOF_SURFACE,
	WALL_SURFACE,	
	DOOR,
	WINDOW,	

	// Bridge
	ABSTRACT_BRIDGE,
	BRIDGE,
	BRIDGE_FURNITURE,
	BRIDGE_CONSTRUCTION_ELEMENT,
	BRIDGE_CONSTRUCTION_ELEMENT_PROPERTY,
	BRIDGE_INSTALLATION,
	BRIDGE_INSTALLATION_PROPERTY,
	BRIDGE_PART,
	BRIDGE_PART_PROPERTY,
	INT_BRIDGE_INSTALLATION,
	INT_BRIDGE_INSTALLATION_PROPERTY,
	BRIDGE_ROOM,	
	INTERIOR_BRIDGE_ROOM_PROPERTY,

	// Building
	ABSTRACT_BUILDING,
	BUILDING,
	BUILDING_FURNITURE,
	BUILDING_INSTALLATION,
	BUILDING_INSTALLATION_PROPERTY,
	BUILDING_PART,
	BUILDING_PART_PROPERTY,
	INT_BUILDING_INSTALLATION,
	INT_BUILDING_INSTALLATION_PROPERTY,
	ROOM,	
	INTERIOR_ROOM_PROPERTY,

	// CityFurniture
	CITY_FURNITURE,

	// CityObjectGroup
	CITY_OBJECT_GROUP,
	CITY_OBJECT_GROUP_MEMBER,
	CITY_OBJECT_GROUP_PARENT,

	// Generics
	ABSTRACT_GENERIC_ATTRIBUTE,
	GENERIC_CITY_OBJECT,
	DATE_ATTRIBUTE,
	DOUBLE_ATTRIBUTE,
	INT_ATTRIBUTE,
	STRING_ATTRIBUTE,
	URI_ATTRIBUTE,
	MEASURE_ATTRIBUTE,
	GENERIC_ATTRIBUTE_SET,

	// LandUse
	LAND_USE,

	// Relief
	ABSTRACT_RELIEF_COMPONENT,	
	RELIEF_FEATURE,
	BREAKLINE_RELIEF,
	GRID_PROPERTY,
	MASSPOINT_RELIEF,
	RASTER_RELIEF,
	TIN_RELIEF,
	RELIEF_COMPONENT_PROPERTY,
	TIN_PROPERTY,

	// Transportation
	ABSTRACT_TRANSPORTATION_OBJECT,
	TRANSPORTATION_COMPLEX,	
	AUXILIARY_TRAFFIC_AREA,	
	RAILWAY,	
	ROAD,
	SQUARE,	
	TRACK,
	TRAFFIC_AREA,
	AUXILIARY_TRAFFIC_AREA_PROPERTY,
	TRAFFIC_AREA_PROPERTY,
	
	// Tunnel
	ABSTRACT_TUNNEL,
	TUNNEL,
	TUNNEL_FURNITURE,
	TUNNEL_INSTALLATION,
	TUNNEL_INSTALLATION_PROPERTY,
	TUNNEL_PART,
	TUNNEL_PART_PROPERTY,
	INT_TUNNEL_INSTALLATION,
	INT_TUNNEL_INSTALLATION_PROPERTY,
	HOLLOW_SPACE,	
	INTERIOR_HOLLOW_SPACE_PROPERTY,

	// Vegetation
	ABSTRACT_VEGETATION_OBJECT,
	PLANT_COVER,	
	SOLITARY_VEGETATION_OBJECT,

	// WaterBody
	ABSTRACT_WATER_BOUNDARY_SURFACE,
	ABSTRACT_WATER_OBJECT,
	WATER_BODY,
	WATER_CLOSURE_SURFACE,
	WATER_GROUND_SURFACE,	
	WATER_SURFACE,
	BOUNDED_BY_WATER_SURFACE_PROPERTY,

	// TexturedSurface
	_ABSTRACT_APPEARANCE,
	_MATERIAL,
	_SIMPLE_TEXTURE,
	_TEXTURED_SURFACE,	
	_COLOR,
	_TEXTURE_TYPE,
	_APPEARANCE_PROPERTY;

	public static CityGMLClass fromInt(int i) {
		for (CityGMLClass c : CityGMLClass.values()) {
			if (c.ordinal() == i) {
				return c;
			}
		}

		return UNDEFINED;
	}

}
