package org.citygml4j.model.citygml.cityfurniture;

import java.util.List;

import org.citygml4j.model.citygml.ade.ADEComponent;
import org.citygml4j.model.citygml.core.CityObject;
import org.citygml4j.model.citygml.core.ImplicitRepresentationProperty;
import org.citygml4j.model.gml.GeometryProperty;
import org.citygml4j.model.gml.MultiCurveProperty;

public interface CityFurniture extends CityObject {
	public String getClazz();
	public List<String> getFunction();
	public GeometryProperty getLod1Geometry();
	public GeometryProperty getLod2Geometry();
	public GeometryProperty getLod3Geometry();
	public GeometryProperty getLod4Geometry();
	public MultiCurveProperty getLod1TerainIntersection();
	public MultiCurveProperty getLod2TerainIntersection();
	public MultiCurveProperty getLod3TerainIntersection();
	public MultiCurveProperty getLod4TerainIntersection();
	public ImplicitRepresentationProperty getLod1ImplicitRepresentation();
	public ImplicitRepresentationProperty getLod2ImplicitRepresentation();
	public ImplicitRepresentationProperty getLod3ImplicitRepresentation();
	public ImplicitRepresentationProperty getLod4ImplicitRepresentation();
	public List<ADEComponent> getGenericApplicationPropertyOfCityFurniture();
	public boolean isSetClazz();
	public boolean isSetFunction();
	public boolean isSetLod1Geometry();
	public boolean isSetLod2Geometry();
	public boolean isSetLod3Geometry();
	public boolean isSetLod4Geometry();
	public boolean isSetLod1TerainIntersection();
	public boolean isSetLod2TerainIntersection();
	public boolean isSetLod3TerainIntersection();
	public boolean isSetLod4TerainIntersection();
	public boolean isSetLod1ImplicitRepresentation();
	public boolean isSetLod2ImplicitRepresentation();
	public boolean isSetLod3ImplicitRepresentation();
	public boolean isSetLod4ImplicitRepresentation();
	public boolean isSetGenericApplicationPropertyOfCityFurniture();
	
	public void setClazz(String clazz);
	public void setFunction(List<String> function);
	public void addFunction(String function);
	public void setLod1Geometry(GeometryProperty lod1Geometry);
	public void setLod2Geometry(GeometryProperty lod2Geometry);
	public void setLod3Geometry(GeometryProperty lod3Geometry);
	public void setLod4Geometry(GeometryProperty lod4Geometry);
	public void setLod1TerainIntersection(MultiCurveProperty lod1TerrainIntersection);
	public void setLod2TerainIntersection(MultiCurveProperty lod2TerrainIntersection);
	public void setLod3TerainIntersection(MultiCurveProperty lod3TerrainIntersection);
	public void setLod4TerainIntersection(MultiCurveProperty lod4TerrainIntersection);
	public void setLod1ImplicitRepresentation(ImplicitRepresentationProperty lod1ImplicitRepresentation);
	public void setLod2ImplicitRepresentation(ImplicitRepresentationProperty lod2ImplicitRepresentation);
	public void setLod3ImplicitRepresentation(ImplicitRepresentationProperty lod3ImplicitRepresentation);
	public void setLod4ImplicitRepresentation(ImplicitRepresentationProperty lod4ImplicitRepresentation);	
	public void addGenericApplicationPropertyOfCityFurniture(ADEComponent adeObject);
	public void setGenericApplicationPropertyOfCityFurniture(List<ADEComponent> adeObject);
	public void unsetClazz();
	public void unsetFunction();
	public boolean unsetFunction(String function);
	public void unsetLod1Geometry();
	public void unsetLod2Geometry();
	public void unsetLod3Geometry();
	public void unsetLod4Geometry();
	public void unsetLod1TerainIntersection();
	public void unsetLod2TerainIntersection();
	public void unsetLod3TerainIntersection();
	public void unsetLod4TerainIntersection();
	public void unsetLod1ImplicitRepresentation();
	public void unsetLod2ImplicitRepresentation();
	public void unsetLod3ImplicitRepresentation();
	public void unsetLod4ImplicitRepresentation();
	public void unsetGenericApplicationPropertyOfCityFurniture();
	public boolean unsetGenericApplicationPropertyOfCityFurniture(ADEComponent adeObject);
}
