module org.citygml4j.core {
    requires transitive org.xmlobjects.gml;
    requires transitive org.xmlobjects.xal;

    exports org.citygml4j.core.ade;
    exports org.citygml4j.core.model;
    exports org.citygml4j.core.model.ade;
    exports org.citygml4j.core.model.ade.generic;
    exports org.citygml4j.core.model.appearance;
    exports org.citygml4j.core.model.bridge;
    exports org.citygml4j.core.model.building;
    exports org.citygml4j.core.model.cityfurniture;
    exports org.citygml4j.core.model.cityobjectgroup;
    exports org.citygml4j.core.model.common;
    exports org.citygml4j.core.model.construction;
    exports org.citygml4j.core.model.core;
    exports org.citygml4j.core.model.deprecated;
    exports org.citygml4j.core.model.deprecated.appearance;
    exports org.citygml4j.core.model.deprecated.bridge;
    exports org.citygml4j.core.model.deprecated.building;
    exports org.citygml4j.core.model.deprecated.cityfurniture;
    exports org.citygml4j.core.model.deprecated.cityobjectgroup;
    exports org.citygml4j.core.model.deprecated.construction;
    exports org.citygml4j.core.model.deprecated.core;
    exports org.citygml4j.core.model.deprecated.generics;
    exports org.citygml4j.core.model.deprecated.transportation;
    exports org.citygml4j.core.model.deprecated.tunnel;
    exports org.citygml4j.core.model.deprecated.vegetation;
    exports org.citygml4j.core.model.deprecated.waterbody;
    exports org.citygml4j.core.model.dynamizer;
    exports org.citygml4j.core.model.generics;
    exports org.citygml4j.core.model.landuse;
    exports org.citygml4j.core.model.pointcloud;
    exports org.citygml4j.core.model.relief;
    exports org.citygml4j.core.model.transportation;
    exports org.citygml4j.core.model.tunnel;
    exports org.citygml4j.core.model.vegetation;
    exports org.citygml4j.core.model.versioning;
    exports org.citygml4j.core.model.waterbody;
    exports org.citygml4j.core.util;
    exports org.citygml4j.core.util.geometry;
    exports org.citygml4j.core.util.reference;
    exports org.citygml4j.core.visitor;

    opens org.citygml4j.core.model to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.ade to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.ade.generic to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.appearance to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.bridge to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.building to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.cityfurniture to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.cityobjectgroup to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.common to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.construction to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.core to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.appearance to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.bridge to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.building to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.cityfurniture to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.cityobjectgroup to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.construction to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.core to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.generics to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.transportation to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.tunnel to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.vegetation to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.deprecated.waterbody to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.dynamizer to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.generics to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.landuse to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.pointcloud to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.relief to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.transportation to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.tunnel to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.vegetation to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.versioning to org.xmlobjects.gml, org.xmlobjects;
    opens org.citygml4j.core.model.waterbody to org.xmlobjects.gml, org.xmlobjects;
}